name: Minimal console build and test

on:
  pull_request:
    branches:
      - main
      - test-nurs
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
      - test-nurs
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: Build and run minimal console app
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create object file
      run: .\tools\as.exe .\min-exe\con-app-aarch64.s -o con-app-aarch64.o
    
    # - name: Test console app
    #   run: |
    #     $env:PATH
    #     $Environment = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
    #     foreach ($path in ($Environment).Split(";"))
    #       {
    #       if ($path -like "*\usr\bin*")
    #         {
    #           $Environment = $Environment.Replace($path ,"")
    #         }
    #       }
    #     [System.Environment]::SetEnvironmentVariable("Path", $Environment, "Machine")
    #     $env:PATH
    #     $Remove = 'C:\Program Files\Git\usr\bin'
    #     $env:Path = ($env:Path.Split(';') | Where-Object -FilterScript {$_ -ne $Remove}) -join ';'
    #     $env:PATH


    - name: Remove /usr/bin/link
      run: |
        $Remove = 'C:\Program Files\Git\usr\bin'
        $env:Path = ($env:Path.Split(';') | Where-Object -FilterScript {$_ -ne $Remove}) -join ';'
        $env:PATH

    - name: Configure build for arm64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_arm64

    - name: Link object file
      run: LINK con-app-aarch64.o kernel32.Lib /SUBSYSTEM:CONSOLE

    - name: Run console app
      run: ls

    - name: Run console app
      run: .\con-app-aarch64.exe
