name: Minimal console build and test


on:
  pull_request:
    branches:
      - main
      - test-nurs
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
      - test-nurs
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create object file
      run: .\tools\as.exe .\min-exe\con-app-aarch64.s -o con-app-aarch64.o
    
    - name: Test console app
      shell: cmd
      run: rm "C:\Program Files\Git\usr\bin\link.exe"


    - name: Link object file
      run: |
        link con-app-aarch64.o kernel32.Lib /SUBSYSTEM:CONSOLE

    - name: Test console app
      run: cmd con-app-aarch64.exe

