name: Minimal console app build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**/*.md'
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: Build, test, create artifact
    runs-on: [self-hosted, Windows, ARM64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create object file
      run: .\tools\as.exe .\min-exe\con-app-aarch64.s -o con-app-aarch64.o

    - name: Link object file
      run: LINK con-app-aarch64.o kernel32.Lib /SUBSYSTEM:CONSOLE

    - name: Dumpbin the executable
      run: DUMPBIN /HEADERS .\con-app-aarch64.exe

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: min-console-exe
        path: .\con-app-aarch64.exe

    - name: Run minimal console app
      run: .\con-app-aarch64.exe
    
    - name: Run assert script
      run: .\.github\workflows\scripts\assert-output.ps1
