name: Minimal console app build

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: Build and upload minimal console app
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create object file
      run: .\tools\as.exe .\min-exe\con-app-aarch64.s -o con-app-aarch64.o

    # # Uncomment in case there will be an issue with path overwrite by git/usr/bin/link
    # - name: Remove /usr/bin/link
    #   run: |
    #     $Remove = 'C:\Program Files\Git\usr\bin'
    #     $env:Path = ($env:Path.Split(';') | Where-Object -FilterScript {$_ -ne $Remove}) -join ';'
    #     $env:PATH

    - name: Configure build for arm64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_arm64

    - name: Link object file
      run: LINK con-app-aarch64.o kernel32.Lib /SUBSYSTEM:CONSOLE

    - name: Dumpbin the executable
      run: DUMPBIN /HEADERS .\con-app-aarch64.exe

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: min-console-exe
        path: .\con-app-aarch64.exe


  test:
    name: Run and assert the output of app run
    runs-on: [self-hosted, Windows, ARM64]
    needs: build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: min-console-exe

    - name: Run assert script
      run: | 
        .\.github\workflows\scripts\assert-output.ps1 | Out-Null


