name: Minimal console build and test


on:
  pull_request:
    branches:
      - main
      - test-nurs
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
      - test-nurs
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    - name: Build and run minimal console app
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create object file
      run: .\tools\as.exe .\min-exe\con-app-aarch64.s -o con-app-aarch64.o
    
    # - name: Test console app
    #   run: |
    #     $Environment = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
    #     foreach ($path in ($Environment).Split(";"))
    #       {
    #       if ($path -like "*\usr\bin*")
    #         {
    #           $Environment = $Environment.Replace($Path ,"")
    #         }
    #       }
    #     [System.Environment]::SetEnvironmentVariable("Path", $Environment, "Machine")


    - name: Link object file
      run: cmd link con-app-aarch64.o kernel32.Lib /SUBSYSTEM:CONSOLE

    - name: Run console app
      run: cmd con-app-aarch64.exe

