name: Minimal console build and test


on:
  pull_request:
    branches:
      - main
      - test-nurs
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
      - test-nurs
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create object file
      run: .\tools\as.exe .\min-exe\con-app-aarch64.s -o con-app-aarch64.o
    
    - name: Link object file
      run: |
        cmd link con-app-aarch64.o kernel32.Lib /SUBSYSTEM:CONSOLE /OUT:${{ github.workspace}}\con-app-aarch64.exe

    - name: Test console app
      run: cmd con-app-aarch64.exe

    - name: Test console app
      run: mkdir build
    - name: Test console app
      run: cmd copy .\con-app-aarch64.exe ${{ github.workspace}}\build
    - name: Test console app
      run: |
      ls
      cd build
      ls
